apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-lab5p2-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-lab5p2-flask-app
  template:
    metadata:
      labels:
        app: cloud-lab5p2-flask-app
    spec:
      containers:
        - name: cloud-lab5p2-flask-app
          image: labo5test.azurecr.io/cloud-lab5p2-flask-app
          ports:
            - containerPort: 80
